#!/bin/bash

export LITECOIN_P2P_PORT=9333
export LITECOIN_NODE_IP=litecoin
export LITECOIN_RPC_PORT=9332
export LITECOIN_LOCAL_IP=umbrel.local
export LITECOIN_RPC_USER=testuser
export LITECOIN_RPC_PASS=testpass
export LITECOIN_NODE_NETWORK=mainnet
export LITECOIN_LOCALHOST_IP=litecoin_node_rpc_flesk